apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - webserver-deployment.yaml
  - webserver-service.yaml
images:
  - name: nginx
    newName: 790110293514.dkr.ecr.us-east-2.amazonaws.com/webserver # {"$imagepolicy": "flux-system:gitops-demo:name"}
    newTag: main-9323a1d-1625206586 # {"$imagepolicy": "flux-system:gitops-demo:tag"}
